FROM golang:1.22-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -o dashboard-service .

FROM gcr.io/distroless/static:nonroot
COPY --from=builder /app/dashboard-service /
EXPOSE 8080
ENTRYPOINT ["/dashboard-service"]
